// ============================================================
// NOURISHBOX — Rich Mock Data
// ============================================================
import type {
    Meal,
    User,
    FamilyMember,
    WeeklyPlan,
    Subscription,
    Order,
    NourishPoints,
    MacroLog,
    AdminMetrics,
    ChatMessage,
} from "./types";

// --- MEALS ---
export const MOCK_MEALS: Meal[] = [
    // BOWLS & SALADES
    {
        id: "m1",
        slug: "quinoa-poulet-grille",
        name: "Quinoa & Poulet Grillé",
        description: "Bol de quinoa croquant avec poulet grillé et légumes.",
        category: "lunch",
        image_url: "/menu/bol-quinoa-and-poulet-grille.jpg",
        emoji: "🥗",
        macros: { kcal: 520, protein_g: 42, carbs_g: 48, fats_g: 12 },
        prep_time_min: 25,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: [],
        tags: ["Protéiné", "GF", "Featured"],
        is_active: true,
        price_mad: 75,
        tier: "standard",
    },
    {
        id: "m2",
        slug: "nicoise-thon-oeuf-mollet",
        name: "Niçoise Thon & Œuf Mollet",
        description: "Salade Niçoise classique avec thon et œuf mollet.",
        category: "lunch",
        image_url: "/menu/thon-au-naturel.jpg",
        emoji: "🥙",
        macros: { kcal: 410, protein_g: 36, carbs_g: 22, fats_g: 18 },
        prep_time_min: 20,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: ["fish", "eggs"],
        tags: ["Keto", "GF", "Featured"],
        is_active: true,
        price_mad: 73,
        tier: "standard",
    },
    {
        id: "m3",
        slug: "salade-fruits-maison",
        name: "Salade de Fruits Maison",
        description: "Mélange de fruits frais de saison.",
        category: "snack",
        image_url: "/menu/salade-de-fruits.jpg",
        emoji: "🍉",
        macros: { kcal: 220, protein_g: 4, carbs_g: 52, fats_g: 2 },
        prep_time_min: 10,
        is_vegan: true,
        is_halal: true,
        is_gluten_free: true,
        allergens: [],
        tags: ["Vegan", "GF"],
        is_active: true,
        price_mad: 45,
        tier: "budget",
    },
    // POISSON & FRUITS DE MER
    {
        id: "m4",
        slug: "saumon-grille-legumes",
        name: "Saumon Grillé & Légumes",
        description: "Saumon grillé parfaitement avec des légumes sautés.",
        category: "dinner",
        image_url: "/menu/power-saumon.jpg",
        emoji: "🐟",
        macros: { kcal: 480, protein_g: 46, carbs_g: 28, fats_g: 18 },
        prep_time_min: 30,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: ["fish"],
        tags: ["Protéiné", "GF", "Featured"],
        is_active: true,
        price_mad: 95,
        tier: "premium",
    },
    {
        id: "m5",
        slug: "saumon-aneth-puree",
        name: "Saumon Aneth & Purée",
        description: "Saumon à l'aneth servi avec une purée onctueuse.",
        category: "dinner",
        image_url: "/menu/saumon-aneth.jpg",
        emoji: "🍣",
        macros: { kcal: 440, protein_g: 38, carbs_g: 32, fats_g: 16 },
        prep_time_min: 30,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: ["fish", "dairy"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 92,
        tier: "premium",
    },
    {
        id: "m6",
        slug: "tartare-poisson-frais",
        name: "Tartare de Poisson Frais",
        description: "Tartare de poisson frais assaisonné.",
        category: "lunch",
        image_url: "/menu/fush-tartar.jpg",
        emoji: "🥣",
        macros: { kcal: 320, protein_g: 28, carbs_g: 14, fats_g: 16 },
        prep_time_min: 15,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: ["fish"],
        tags: ["Keto", "GF", "Featured"],
        is_active: true,
        price_mad: 85,
        tier: "standard",
    },
    {
        id: "m7",
        slug: "burger-poisson-capres",
        name: "Burger Poisson & Câpres",
        description: "Burger de poisson délicieux avec des câpres.",
        category: "lunch",
        image_url: "/menu/fish-burger.jpg",
        emoji: "🍔",
        macros: { kcal: 490, protein_g: 32, carbs_g: 44, fats_g: 18 },
        prep_time_min: 20,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["fish", "gluten"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 78,
        tier: "standard",
    },
    {
        id: "m8",
        slug: "crevettes-ail-piment",
        name: "Crevettes Ail & Piment",
        description: "Crevettes sautées à l'ail et au piment.",
        category: "dinner",
        image_url: "/menu/crevettes-pilpil.jpg",
        emoji: "🍤",
        macros: { kcal: 360, protein_g: 34, carbs_g: 18, fats_g: 16 },
        prep_time_min: 15,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: ["shellfish"],
        tags: ["Keto", "GF", "Featured"],
        is_active: true,
        price_mad: 88,
        tier: "standard",
    },
    {
        id: "m9",
        slug: "gambas-grillees-riz",
        name: "Gambas Grillées & Riz",
        description: "Gambas grillées servies avec du riz basmati.",
        category: "dinner",
        image_url: "/menu/power-crevettes.jpg",
        emoji: "🦐",
        macros: { kcal: 420, protein_g: 40, carbs_g: 34, fats_g: 10 },
        prep_time_min: 25,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: ["shellfish"],
        tags: ["Protéiné", "GF", "Featured"],
        is_active: true,
        price_mad: 95,
        tier: "premium",
    },
    {
        id: "m10",
        slug: "sardines-marinees-citron",
        name: "Sardines Marinées Citron",
        description: "Sardines fraîches marinées au citron.",
        category: "lunch",
        image_url: "/menu/sardines-marinees.jpg",
        emoji: "🐟",
        macros: { kcal: 380, protein_g: 32, carbs_g: 16, fats_g: 20 },
        prep_time_min: 15,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: ["fish"],
        tags: ["Keto", "GF"],
        is_active: true,
        price_mad: 65,
        tier: "budget",
    },
    {
        id: "m11",
        slug: "sardines-couscous-chermoula",
        name: "Sardines & Couscous Chermoula",
        description: "Sardines grillées avec couscous à la chermoula.",
        category: "dinner",
        image_url: "/menu/power-sardin.jpg",
        emoji: "🥘",
        macros: { kcal: 450, protein_g: 34, carbs_g: 38, fats_g: 14 },
        prep_time_min: 30,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["fish", "gluten"],
        tags: ["Protéiné"],
        is_active: true,
        price_mad: 75,
        tier: "standard",
    },
    {
        id: "m12",
        slug: "spaghetti-saumon-aneth",
        name: "Spaghetti Saumon Aneth",
        description: "Spaghetti crémeux au saumon et à l'aneth.",
        category: "dinner",
        image_url: "/menu/spaghetti-saumon.jpg",
        emoji: "🍝",
        macros: { kcal: 520, protein_g: 34, carbs_g: 52, fats_g: 16 },
        prep_time_min: 20,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["fish", "gluten", "dairy"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 82,
        tier: "standard",
    },
    {
        id: "m13",
        slug: "wrap-crevettes-cocktail",
        name: "Wrap Crevettes Cocktail",
        description: "Wrap frais aux crevettes cocktail.",
        category: "lunch",
        image_url: "/menu/wrap-crevettes-cocktail.jpg",
        emoji: "🌯",
        macros: { kcal: 440, protein_g: 28, carbs_g: 42, fats_g: 14 },
        prep_time_min: 15,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["shellfish", "gluten"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 72,
        tier: "standard",
    },
    {
        id: "m14",
        slug: "wrap-crevettes-jalapeno-truffe",
        name: "Wrap Crevettes Jalapeño Truffe",
        description: "Wrap gourmand aux crevettes, jalapeño et truffe.",
        category: "lunch",
        image_url: "/menu/wrap-crevette-jalapeno-truffes.jpg",
        emoji: "🌯",
        macros: { kcal: 480, protein_g: 30, carbs_g: 40, fats_g: 18 },
        prep_time_min: 15,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["shellfish", "gluten"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 80,
        tier: "premium",
    },
    // POULET
    {
        id: "m15",
        slug: "poulet-buffalo",
        name: "Poulet Buffalo",
        description: "Aiguillettes de poulet épicées à la sauce Buffalo.",
        category: "lunch",
        image_url: "/menu/chicken-buffalo.jpg",
        emoji: "🍗",
        macros: { kcal: 480, protein_g: 44, carbs_g: 32, fats_g: 16 },
        prep_time_min: 20,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: ["dairy"],
        tags: ["Protéiné", "Featured"],
        is_active: true,
        price_mad: 78,
        tier: "standard",
    },
    {
        id: "m16",
        slug: "poulet-sauce-dynamite",
        name: "Poulet Sauce Dynamite",
        description: "Poulet croustillant avec sauce dynamite piquante.",
        category: "lunch",
        image_url: "/menu/chicken-dynamite.jpg",
        emoji: "🍗",
        macros: { kcal: 460, protein_g: 40, carbs_g: 30, fats_g: 16 },
        prep_time_min: 20,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["gluten", "eggs"],
        tags: ["Protéiné"],
        is_active: true,
        price_mad: 78,
        tier: "standard",
    },
    {
        id: "m17",
        slug: "poulet-safran-coco",
        name: "Poulet Safran & Coco",
        description: "Poulet tendre mijoté au safran et lait de coco.",
        category: "dinner",
        image_url: "/menu/chicken-safran-coco.jpg",
        emoji: "🍛",
        macros: { kcal: 520, protein_g: 38, carbs_g: 36, fats_g: 20 },
        prep_time_min: 30,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: [],
        tags: ["GF"],
        is_active: true,
        price_mad: 82,
        tier: "standard",
    },
    {
        id: "m18",
        slug: "poulet-tandoori",
        name: "Poulet Tandoori",
        description: "Poulet mariné aux épices tandoori.",
        category: "dinner",
        image_url: "/menu/chicken-tandoori.jpg",
        emoji: "🍗",
        macros: { kcal: 420, protein_g: 42, carbs_g: 18, fats_g: 14 },
        prep_time_min: 25,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: ["dairy"],
        tags: ["Keto", "GF"],
        is_active: true,
        price_mad: 75,
        tier: "standard",
    },
    {
        id: "m19",
        slug: "tenders-dores",
        name: "Tenders Dorés",
        description: "Filets de poulet panés et dorés à souhait.",
        category: "snack",
        image_url: "/menu/chicken-tenders.jpg",
        emoji: "🍗",
        macros: { kcal: 480, protein_g: 38, carbs_g: 40, fats_g: 16 },
        prep_time_min: 15,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["gluten", "eggs"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 65,
        tier: "standard",
    },
    {
        id: "m20",
        slug: "poulet-tandoori-quinoa",
        name: "Poulet Tandoori & Quinoa",
        description: "Assemblage nutritionnel de poulet tandoori et quinoa.",
        category: "lunch",
        image_url: "/menu/power-chicken-tandoori.jpg",
        emoji: "🥗",
        macros: { kcal: 540, protein_g: 52, carbs_g: 38, fats_g: 14 },
        prep_time_min: 25,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: ["dairy"],
        tags: ["Protéiné", "GF", "Booster", "Featured"],
        is_active: true,
        price_mad: 85,
        tier: "premium",
    },
    {
        id: "m21",
        slug: "poulet-curry-riz",
        name: "Poulet Curry & Riz",
        description: "Curry de poulet classique servi avec du riz.",
        category: "dinner",
        image_url: "/menu/poulet-curry.jpg",
        emoji: "🍛",
        macros: { kcal: 510, protein_g: 40, carbs_g: 44, fats_g: 14 },
        prep_time_min: 30,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: [],
        tags: ["GF"],
        is_active: true,
        price_mad: 78,
        tier: "standard",
    },
    {
        id: "m22",
        slug: "burger-poulet-tartare",
        name: "Burger Poulet Tartare",
        description: "Burger de poulet avec une sauce tartare onctueuse.",
        category: "lunch",
        image_url: "/menu/burger-chicken-tartar.jpg",
        emoji: "🍔",
        macros: { kcal: 520, protein_g: 36, carbs_g: 46, fats_g: 18 },
        prep_time_min: 20,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["gluten", "eggs"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 78,
        tier: "standard",
    },
    {
        id: "m23",
        slug: "wrap-poulet-tandoori",
        name: "Wrap Poulet Tandoori",
        description: "Wrap savoureux garni de poulet tandoori.",
        category: "lunch",
        image_url: "/menu/wrap-poulet-tandoori.jpg",
        emoji: "🌯",
        macros: { kcal: 460, protein_g: 36, carbs_g: 44, fats_g: 14 },
        prep_time_min: 15,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["gluten", "dairy"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 72,
        tier: "standard",
    },
    {
        id: "m24",
        slug: "wrap-tenders-moutarde",
        name: "Wrap Tenders Moutarde",
        description: "Wrap gourmand aux tenders et sauce moutarde.",
        category: "lunch",
        image_url: "/menu/wrap-poulet-tenders.jpg",
        emoji: "🌯",
        macros: { kcal: 480, protein_g: 34, carbs_g: 46, fats_g: 16 },
        prep_time_min: 15,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["gluten", "eggs", "mustard"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 70,
        tier: "standard",
    },
    // VIANDES
    {
        id: "m25",
        slug: "boeuf-farci-herbes",
        name: "Bœuf Farci aux Herbes",
        description: "Émincé de bœuf farci aux herbes aromatiques.",
        category: "dinner",
        image_url: "/menu/boeuf-farcie.jpg",
        emoji: "🥩",
        macros: { kcal: 560, protein_g: 46, carbs_g: 28, fats_g: 24 },
        prep_time_min: 35,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: [],
        tags: ["GF"],
        is_active: true,
        price_mad: 95,
        tier: "premium",
    },
    {
        id: "m26",
        slug: "double-boeuf-poulet-grille",
        name: "Double Bœuf & Poulet Grillé",
        description: "Un festin pour les amateurs de viande : bœuf et poulet grillés.",
        category: "dinner",
        image_url: "/menu/lion's-share.jpg",
        emoji: "🍖",
        macros: { kcal: 680, protein_g: 62, carbs_g: 30, fats_g: 28 },
        prep_time_min: 40,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: [],
        tags: ["Protéiné", "Keto", "GF"],
        is_active: true,
        price_mad: 110,
        tier: "premium",
    },
    {
        id: "m27",
        slug: "boeuf-patate-douce",
        name: "Bœuf & Patate Douce",
        description: "Morceaux de bœuf tendres accompagnés de patate douce.",
        category: "dinner",
        image_url: "/menu/power-beef.jpg",
        emoji: "🥩",
        macros: { kcal: 580, protein_g: 52, carbs_g: 38, fats_g: 20 },
        prep_time_min: 30,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: [],
        tags: ["Protéiné", "GF"],
        is_active: true,
        price_mad: 92,
        tier: "premium",
    },
    {
        id: "m28",
        slug: "burger-boeuf-sauce-dynamite",
        name: "Burger Bœuf Sauce Dynamite",
        description: "Burger de bœuf savoureux avec sauce dynamite.",
        category: "lunch",
        image_url: "/menu/burger-dynamite.jpg",
        emoji: "🍔",
        macros: { kcal: 620, protein_g: 42, carbs_g: 50, fats_g: 26 },
        prep_time_min: 20,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["gluten", "eggs"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 85,
        tier: "standard",
    },
    // PÂTES & NOUILLES
    {
        id: "m29",
        slug: "spaghetti-boeuf-maison",
        name: "Spaghetti Bœuf Maison",
        description: "Spaghetti à la bolognaise maison façon Nourishbox.",
        category: "dinner",
        image_url: "/menu/spaghetti-bolognaise.jpg",
        emoji: "🍝",
        macros: { kcal: 580, protein_g: 38, carbs_g: 62, fats_g: 16 },
        prep_time_min: 25,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["gluten"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 78,
        tier: "standard",
    },
    {
        id: "m30",
        slug: "spaghetti-boeuf-basilic-thai",
        name: "Spaghetti Bœuf Basilic Thaï",
        description: "Spaghetti sautés au bœuf et basilic thaï.",
        category: "dinner",
        image_url: "/menu/spaghetti-beef-thai.jpg",
        emoji: "🍝",
        macros: { kcal: 560, protein_g: 36, carbs_g: 58, fats_g: 16 },
        prep_time_min: 25,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["gluten", "soy"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 82,
        tier: "standard",
    },
    {
        id: "m31",
        slug: "noodles-boeuf-tamarin",
        name: "Noodles Bœuf Tamarin",
        description: "Nouilles au bœuf avec une sauce tamarin acidulée.",
        category: "dinner",
        image_url: "/menu/noodles-beef-thai.jpg",
        emoji: "🍜",
        macros: { kcal: 520, protein_g: 34, carbs_g: 54, fats_g: 14 },
        prep_time_min: 20,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["gluten", "soy"],
        tags: ["Booster", "Featured"],
        is_active: true,
        price_mad: 80,
        tier: "standard",
    },
    {
        id: "m32",
        slug: "noodles-crevettes-thai",
        name: "Noodles Crevettes Thaï",
        description: "Nouilles sautées aux crevettes façon thaïlandaise.",
        category: "dinner",
        image_url: "/menu/noodle-crevette-thai.jpg",
        emoji: "🍜",
        macros: { kcal: 480, protein_g: 32, carbs_g: 52, fats_g: 12 },
        prep_time_min: 20,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["shellfish", "gluten", "soy"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 85,
        tier: "premium",
    },
    {
        id: "m33",
        slug: "noodles-poulet-citronnelle",
        name: "Noodles Poulet Citronnelle",
        description: "Nouilles parfumées à la citronnelle avec du poulet.",
        category: "dinner",
        image_url: "/menu/noodles-poulet-thai.jpg",
        emoji: "🍜",
        macros: { kcal: 500, protein_g: 36, carbs_g: 50, fats_g: 12 },
        prep_time_min: 20,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["gluten", "soy"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 78,
        tier: "standard",
    },
    // BURGERS & WRAPS
    {
        id: "m34",
        slug: "croustillant-poulet-dijon",
        name: "Croustillant Poulet Dijon",
        description: "Sandwich au poulet croustillant et moutarde de Dijon.",
        category: "lunch",
        image_url: "/menu/french-crispy.jpg",
        emoji: "🥪",
        macros: { kcal: 500, protein_g: 38, carbs_g: 40, fats_g: 18 },
        prep_time_min: 20,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["gluten", "mustard"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 75,
        tier: "standard",
    },
    {
        id: "m35",
        slug: "tacos-tenders-avocat",
        name: "Tacos Tenders & Avocat",
        description: "Tacos garnis de tenders de poulet et d'avocat.",
        category: "lunch",
        image_url: "/menu/tacos-chicken-tenders.jpg",
        emoji: "🌮",
        macros: { kcal: 560, protein_g: 36, carbs_g: 50, fats_g: 20 },
        prep_time_min: 15,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["gluten", "dairy"],
        tags: ["Featured"],
        is_active: true,
        price_mad: 82,
        tier: "standard",
    },
    // PETIT-DÉJEUNER & BOWLS SUCRÉS
    {
        id: "m36",
        slug: "chia-coco-fruits-exotiques",
        name: "Chia Coco & Fruits Exotiques",
        description: "Pudding de chia au coco avec fruits exotiques.",
        category: "breakfast",
        image_url: "/menu/chia-exotique.jpg",
        emoji: "🥣",
        macros: { kcal: 360, protein_g: 8, carbs_g: 46, fats_g: 14 },
        prep_time_min: 10,
        is_vegan: true,
        is_halal: true,
        is_gluten_free: true,
        allergens: [],
        tags: ["Vegan", "GF"],
        is_active: true,
        price_mad: 55,
        tier: "standard",
    },
    {
        id: "m37",
        slug: "toast-beurre-cacahuete-fruits",
        name: "Toast Beurre de Cacahuète & Fruits",
        description: "Toast croquant au beurre de cacahuète et fruits frais.",
        category: "breakfast",
        image_url: "/menu/PB-and-J-flow.jpg",
        emoji: "🍞",
        macros: { kcal: 420, protein_g: 14, carbs_g: 52, fats_g: 16 },
        prep_time_min: 10,
        is_vegan: true,
        is_halal: true,
        is_gluten_free: false,
        allergens: ["gluten", "peanuts"],
        tags: ["Vegan"],
        is_active: true,
        price_mad: 48,
        tier: "standard",
    },
    // PLATS MIJOTÉS & MAROCAINS
    {
        id: "m38",
        slug: "tagine-lentilles-epices",
        name: "Tagine Lentilles & Épices",
        description: "Tagine de lentilles savoureux aux épices marocaines.",
        category: "dinner",
        image_url: "/menu/tagine-de-lentille-au-epices.jpg",
        emoji: "🍲",
        macros: { kcal: 490, protein_g: 22, carbs_g: 62, fats_g: 10 },
        prep_time_min: 40,
        is_vegan: true,
        is_halal: true,
        is_gluten_free: true,
        allergens: [],
        tags: ["Vegan", "GF"],
        is_active: true,
        price_mad: 68,
        tier: "standard",
    },
    // DESSERTS & SNACKS
    {
        id: "m39",
        slug: "brownie-chocolat-coco",
        name: "Brownie Chocolat Coco",
        description: "Brownie fondant au chocolat et noix de coco.",
        category: "snack",
        image_url: "/menu/fludge-coco-banane.jpg",
        emoji: "🍫",
        macros: { kcal: 280, protein_g: 8, carbs_g: 36, fats_g: 12 },
        prep_time_min: 5,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: ["eggs"],
        tags: ["GF"],
        is_active: true,
        price_mad: 42,
        tier: "budget",
    },
    {
        id: "m40",
        slug: "fudge-chocolat-banane",
        name: "Fudge Chocolat Banane",
        description: "Fudge vegan au chocolat et à la banane.",
        category: "snack",
        image_url: "/menu/fludge-coco-banane.jpg",
        emoji: "🍫",
        macros: { kcal: 260, protein_g: 6, carbs_g: 38, fats_g: 10 },
        prep_time_min: 5,
        is_vegan: true,
        is_halal: true,
        is_gluten_free: true,
        allergens: [],
        tags: ["Vegan", "GF"],
        is_active: true,
        price_mad: 40,
        tier: "budget",
    },
    {
        id: "m41",
        slug: "tiramisu-pistache",
        name: "Tiramisu Pistache",
        description: "Tiramisu healthy à la pistache.",
        category: "snack",
        image_url: "/menu/tiramisu-pistache-healthy.jpg",
        emoji: "🍰",
        macros: { kcal: 320, protein_g: 10, carbs_g: 38, fats_g: 14 },
        prep_time_min: 10,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: ["dairy", "nuts"],
        tags: ["GF"],
        is_active: true,
        price_mad: 55,
        tier: "standard",
    },
    {
        id: "m42",
        slug: "tiramisu-safran",
        name: "Tiramisu Safran",
        description: "Tiramisu raffiné infusé au safran.",
        category: "snack",
        image_url: "/menu/tiramisu-safran.jpg",
        emoji: "🍰",
        macros: { kcal: 310, protein_g: 8, carbs_g: 40, fats_g: 12 },
        prep_time_min: 10,
        is_vegan: false,
        is_halal: true,
        is_gluten_free: true,
        allergens: ["dairy"],
        tags: ["GF"],
        is_active: true,
        price_mad: 58,
        tier: "premium",
    },
];

// --- CURRENT USER ---
export const MOCK_USER: User = {
    id: "u1",
    name: "Yasmine El Mansouri",
    email: "yasmine@example.ma",
    avatar_color: "#6BC4A0",
    goal: "muscle_gain",
    persona: "professional",
    activity_level: "moderate",
    height_cm: 165,
    weight_kg: 60,
    age: 29,
    gender: "female",
    daily_targets: {
        kcal: 1950,
        protein_g: 146,
        carbs_g: 219,
        fats_g: 54,
    },
    language: "fr",
};

// --- TODAY'S CONSUMED MACROS ---
export const MOCK_TODAY_CONSUMED: { kcal: number; protein_g: number; carbs_g: number; fats_g: number } = {
    kcal: 1340,
    protein_g: 98,
    carbs_g: 152,
    fats_g: 36,
};

// --- FAMILY MEMBERS ---
export const MOCK_FAMILY_MEMBERS: FamilyMember[] = [
    {
        id: "f1",
        name: "Yasmine",
        relation: "self",
        avatar_color: "#6BC4A0",
        age: 29,
        goal: "muscle_gain",
        daily_kcal: 1950,
        assigned_meal_ids: ["m1", "m4", "m20"],
    },
    {
        id: "f2",
        name: "Karim",
        relation: "partner",
        avatar_color: "#B09AE0",
        age: 32,
        goal: "maintenance",
        daily_kcal: 2400,
        assigned_meal_ids: ["m27", "m26", "m15"],
    },
    {
        id: "f3",
        name: "Lina",
        relation: "child",
        avatar_color: "#FFA07A",
        age: 8,
        goal: "balance",
        daily_kcal: 1600,
        assigned_meal_ids: ["m19", "m11", "m40"],
    },
    {
        id: "f4",
        name: "Mama",
        relation: "parent",
        avatar_color: "#FFD3B6",
        age: 58,
        goal: "weight_loss",
        daily_kcal: 1400,
        assigned_meal_ids: ["m2", "m38", "m10"],
    },
];

// --- WEEKLY PLAN ---
export const MOCK_WEEKLY_PLAN: WeeklyPlan = {
    id: "wp1",
    week_offset: 0,
    confirmed: false,
    paused_days: [5], // Saturday paused
    planned_meals: [
        // Monday (0)
        { id: "pm1", meal_id: "m18", day_index: 0, family_member_id: "f1", status: "planned" },
        { id: "pm2", meal_id: "m1", day_index: 0, family_member_id: "f1", status: "planned" },
        { id: "pm3", meal_id: "m4", day_index: 0, family_member_id: "f1", status: "planned" },
        // Tuesday (1)
        { id: "pm4", meal_id: "m36", day_index: 1, family_member_id: "f1", status: "planned" },
        { id: "pm5", meal_id: "m2", day_index: 1, family_member_id: "f1", status: "planned" },
        { id: "pm6", meal_id: "m15", day_index: 1, family_member_id: "f1", status: "planned" },
        // Wednesday (2)
        { id: "pm7", meal_id: "m37", day_index: 2, family_member_id: "f1", status: "planned" },
        { id: "pm8", meal_id: "m10", day_index: 2, family_member_id: "f1", status: "planned" },
        { id: "pm9", meal_id: "m38", day_index: 2, family_member_id: "f1", status: "planned" },
        // Thursday (3)
        { id: "pm10", meal_id: "m41", day_index: 3, family_member_id: "f1", status: "planned" },
        { id: "pm11", meal_id: "m22", day_index: 3, family_member_id: "f1", status: "planned" },
        { id: "pm12", meal_id: "m27", day_index: 3, family_member_id: "f1", status: "planned" },
        // Friday (4)
        { id: "pm13", meal_id: "m18", day_index: 4, family_member_id: "f1", status: "planned" },
        { id: "pm14", meal_id: "m11", day_index: 4, family_member_id: "f1", status: "planned" },
        // Sunday (6)
        { id: "pm15", meal_id: "m36", day_index: 6, family_member_id: "f1", status: "planned" },
        { id: "pm16", meal_id: "m17", day_index: 6, family_member_id: "f1", status: "planned" },
    ],
};

// --- SUBSCRIPTION ---
export const MOCK_SUBSCRIPTION: Subscription = {
    id: "sub1",
    user_id: "u1",
    plan: "balanced_5",
    status: "active",
    price_mad: 890,
    starts_at: "2025-03-01",
    renews_at: "2025-04-01",
};

// --- ORDERS (Kanban) ---
export const MOCK_ORDERS: Order[] = [
    {
        id: "ord1",
        meal_id: "m1",
        meal_name: "Quinoa & Poulet Grillé",
        meal_emoji: "🥗",
        user_name: "Yasmine El Mansouri",
        user_id: "u1",
        status: "pending",
        created_at: "2025-03-20T08:30:00Z",
        address: "12, Rue Anfa, Casablanca",
        total_mad: 75,
    },
    {
        id: "ord2",
        meal_id: "m4",
        meal_name: "Saumon Grillé & Légumes",
        meal_emoji: "🐟",
        user_name: "Karim Benali",
        user_id: "u2",
        status: "pending",
        created_at: "2025-03-20T09:15:00Z",
        address: "45, Bd Zerktouni, Casablanca",
        total_mad: 95,
    },
    {
        id: "ord3",
        meal_id: "m11",
        meal_name: "Sardines & Couscous Chermoula",
        meal_emoji: "🥘",
        user_name: "Fatima Ouali",
        user_id: "u3",
        status: "preparing",
        created_at: "2025-03-20T07:45:00Z",
        address: "8, Résidence Ghandi, Casablanca",
        total_mad: 75,
    },
    {
        id: "ord4",
        meal_id: "m15",
        meal_name: "Poulet Buffalo",
        meal_emoji: "🍗",
        user_name: "Mohamed Chraibi",
        user_id: "u4",
        status: "preparing",
        created_at: "2025-03-20T08:00:00Z",
        address: "33, Rue Ibn Rochd, Casablanca",
        total_mad: 78,
    },
    {
        id: "ord5",
        meal_id: "m2",
        meal_name: "Niçoise Thon & Œuf Mollet",
        meal_emoji: "🥙",
        user_name: "Nadia Alaoui",
        user_id: "u5",
        status: "out_for_delivery",
        created_at: "2025-03-20T07:00:00Z",
        address: "22, Rue Riyad, Casablanca",
        total_mad: 73,
    },
    {
        id: "ord6",
        meal_id: "m27",
        meal_name: "Bœuf & Patate Douce",
        meal_emoji: "🥩",
        user_name: "Younes Tazi",
        user_id: "u6",
        status: "out_for_delivery",
        created_at: "2025-03-20T07:30:00Z",
        address: "5, Bd Massira, Casablanca",
        total_mad: 92,
    },
    {
        id: "ord7",
        meal_id: "m38",
        meal_name: "Tagine Lentilles & Épices",
        meal_emoji: "🍲",
        user_name: "Sara Berrada",
        user_id: "u7",
        status: "delivered",
        created_at: "2025-03-20T06:00:00Z",
        address: "18, Rue Oued Zem, Ain Diab",
        total_mad: 68,
    },
    {
        id: "ord8",
        meal_id: "m3",
        meal_name: "Salade de Fruits Maison",
        meal_emoji: "🍉",
        user_name: "Hamza El Fassi",
        user_id: "u8",
        status: "delivered",
        created_at: "2025-03-20T06:30:00Z",
        address: "10, Bd de la Corniche, Casablanca",
        total_mad: 45,
    },
];

// --- NOURISH POINTS ---
export const MOCK_NOURISH_POINTS: NourishPoints = {
    balance: 1240,
    streak: 12,
    longest_streak: 21,
    plant_stage: "tree",
    last_active: "2025-03-20",
};

// --- ANALYTICS (30 days of macro logs) ---
export const MOCK_MACRO_LOGS: MacroLog[] = Array.from({ length: 30 }, (_, i) => {
    const date = new Date("2025-03-20");
    date.setDate(date.getDate() - (29 - i));
    const adherence = 65 + Math.round(Math.sin(i * 0.4) * 20 + Math.random() * 15);
    return {
        date: date.toISOString().split("T")[0],
        consumed: {
            kcal: Math.round(1400 + Math.random() * 600),
            protein_g: Math.round(90 + Math.random() * 60),
            carbs_g: Math.round(140 + Math.random() * 80),
            fats_g: Math.round(35 + Math.random() * 25),
        },
        target: {
            kcal: 1950,
            protein_g: 146,
            carbs_g: 219,
            fats_g: 54,
        },
        adherence: Math.min(100, Math.max(0, adherence)),
    };
});

// --- ADMIN METRICS ---
export const MOCK_ADMIN_METRICS: AdminMetrics = {
    mrr_mad: 142800,
    active_subscribers: 324,
    delivery_success_rate: 97.2,
    churn_rate: 2.8,
    new_this_week: 18,
    weekly_revenue: [
        { week: "S1 Mars", revenue: 32400 },
        { week: "S2 Mars", revenue: 36200 },
        { week: "S3 Mars", revenue: 38600 },
        { week: "S4 Mars", revenue: 35600 },
        { week: "S1 Avr", revenue: 41800 },
        { week: "S2 Avr", revenue: 44200 },
        { week: "S3 Avr", revenue: 46800 },
        { week: "S4 Avr", revenue: 48000 },
    ],
    top_meals: [
        { meal_id: "m1", name: "Quinoa & Poulet Grillé", orders: 284 },
        { meal_id: "m4", name: "Saumon Grillé & Légumes", orders: 241 },
        { meal_id: "m15", name: "Poulet Buffalo", orders: 198 },
        { meal_id: "m11", name: "Sardines & Couscous", orders: 176 },
        { meal_id: "m27", name: "Bœuf & Patate Douce", orders: 154 },
    ],
};

// --- ADMIN USER LIST ---
export const MOCK_ADMIN_USERS = [
    { id: "u1", name: "Yasmine El Mansouri", email: "yasmine@example.ma", plan: "balanced_5", status: "active", since: "2025-01-15", total_orders: 42 },
    { id: "u2", name: "Karim Benali", email: "karim.b@gmail.com", plan: "premium_7", status: "active", since: "2025-02-03", total_orders: 28 },
    { id: "u3", name: "Fatima Ouali", email: "f.ouali@casanet.ma", plan: "starter_3", status: "paused", since: "2024-12-10", total_orders: 67 },
    { id: "u4", name: "Mohamed Chraibi", email: "m.chraibi@outlook.com", plan: "premium_7", status: "active", since: "2025-01-28", total_orders: 35 },
    { id: "u5", name: "Nadia Alaoui", email: "nadia.alaoui@gmail.com", plan: "balanced_5", status: "active", since: "2025-03-01", total_orders: 14 },
    { id: "u6", name: "Younes Tazi", email: "younes.t@hotmail.com", plan: "starter_3", status: "cancelled", since: "2024-11-05", total_orders: 89 },
    { id: "u7", name: "Sara Berrada", email: "s.berrada@gmail.com", plan: "balanced_5", status: "active", since: "2025-02-14", total_orders: 22 },
    { id: "u8", name: "Hamza El Fassi", email: "hamza.f@gmail.com", plan: "premium_7", status: "active", since: "2025-01-02", total_orders: 58 },
];

// --- INITIAL CLINIC MESSAGES ---
export const MOCK_CLINIC_MESSAGES: ChatMessage[] = [
    {
        id: "cm1",
        role: "assistant",
        content:
            "Bonjour Yasmine ! 👋 Je suis Nourishbot, votre assistant nutritionnel. Comment puis-je vous aider aujourd'hui ? Vous pouvez me poser des questions sur vos macros, votre plan alimentaire ou vos objectifs.",
        timestamp: new Date(Date.now() - 86400000).toISOString(),
    },
];

// --- AI RESPONSE LIBRARY ---
export const AI_RESPONSES: Record<string, string[]> = {
    default: [
        "Excellente question ! En tant que nutritionniste IA, je recommande de vous concentrer sur la qualité de vos aliments avant les quantités. 🌿",
        "D'après votre profil, vous êtes sur la bonne voie ! Continuez vos efforts — chaque petit pas compte. 💪",
        "Je comprends votre préoccupation. L'important est de maintenir un équilibre sur le long terme plutôt que de chercher la perfection quotidienne. 🧘",
    ],
    protein: [
        "Pour votre objectif de prise de masse, vous avez besoin d'environ 1.6g de protéines par kg de poids corporel. Avec 60kg, votre cible est ~96-146g/jour. 💪 Nos repas t'y aident facilement !",
        "Les protéines sont essentielles pour la récupération musculaire. Je vois que vous avez déjà consommé 98g aujourd'hui — très bien ! Visez encore 48g avec votre dîner. 🥩",
    ],
    calories: [
        "Aujourd'hui vous avez consommé 1340 kcal sur votre objectif de 1950 kcal. Il vous reste 610 kcal — parfait pour un dîner complet et équilibré. 🍽️",
        "Votre déficit calorique est en bonne voie. L'important est de ne pas descendre sous 1400 kcal pour maintenir votre métabolisme de base actif. 🔥",
    ],
    vegan: [
        "Pour un régime végane équilibré, pensez à combiner légumineuses + céréales pour obtenir tous les acides aminés essentiels. Nos bowls sont parfaits pour ça ! 🌱",
        "Les sources de protéines végétales comme le tofu, tempeh et légumineuses peuvent tout à fait couvrir vos besoins. Je vous recommande notre gamme végane. 🫙",
    ],
    stress: [
        "Le stress peut affecter significativement vos habitudes alimentaires. Des aliments riches en magnésium comme les amandes et légumes verts peuvent aider. 🧘 Pensez aussi à bien vous hydrater !",
        "Je vous comprends. Dans les périodes de stress, optez pour des repas simples mais nutritifs. Nos bowls sont parfaits — pas de décisions difficiles, juste des bonnes calories. 💚",
    ],
    streak: [
        "Félicitations pour votre streak de 12 jours ! 🌳 Votre plante Nourishbox a bien grandi — encore 9 jours pour atteindre le niveau Forêt ! Vous êtes incroyable.",
        "12 jours consécutifs, c'est fantastique ! La régularité est la clé du succès nutritionnel. Votre corps vous en remercie. 🌱✨",
    ],
};
